name: CI

on:
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/ci.yaml'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Install golint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin 

      - name: Install dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify
      
      - name: Run go vet
        run: make vet

      - name: Lint
        run: make lint

      # - name: Test
      #   run: make test
      
      
    
